export const terminosYCondicionesTitulo = [
    "Por favor, lea atentamente estos términos y condiciones antes de utilizar nuestros servicios de alquiler de autos en línea. Al acceder y utilizar este sitio web, usted acepta estar legalmente vinculado por los siguientes términos y condiciones:",
]

export const terminosYCondicionesLineas = [
    "Servicio Ofrecido: a.Nuestro sitio web ofrece servicios de reserva de alquiler de autos proporcionados por terceros proveedores de alquiler de autos. b.Nos esforzamos por proporcionar información precisa y actualizada sobre los vehículos disponibles, tarifas, políticas de alquiler y otros detalles relevantes.",
    "Reservas: a.Las reservas de vehículos están sujetas a disponibilidad. b.Al realizar una reserva, usted confirma que ha proporcionado información precisa y completa sobre los detalles del alquiler, incluidos los requisitos de seguro, la edad del conductor y otros datos relevantes.",
    "Tarifas y Pagos: a.Las tarifas de alquiler pueden variar según la duración del alquiler, el tipo de vehículo, los extras seleccionados y otros factores. b.Se pueden aplicar cargos adicionales por servicios extra, tales como seguros adicionales, conductor adicional, devolución en una ubicación diferente, etc. c.Los pagos se procesarán de acuerdo con los términos y condiciones del proveedor de alquiler de autos seleccionado durante el proceso de reserva.",
    "Política de Cancelación y Modificación: a.Las políticas de cancelación y modificación varían según el proveedor de alquiler de autos y el tipo de reserva. b.Es responsabilidad del cliente revisar y comprender las políticas de cancelación y modificación antes de realizar una reserva.",
    "Responsabilidades del Cliente: a.El cliente es responsable de cumplir con los términos y condiciones del proveedor de alquiler de autos, incluido el uso adecuado del vehículo y el cumplimiento de las leyes de tráfico locales. b.El cliente es responsable de devolver el vehículo en las mismas condiciones en que lo recibió, con el nivel de combustible acordado y dentro del plazo establecido.",
    "Responsabilidad Limitada: a.ArrancAR no se hace responsable de cualquier pérdida, daño, lesión o gasto resultante del uso o la imposibilidad de usar nuestros servicios, incluyendo, pero no limitado a, la cancelación o modificación de reservas, problemas con el vehículo alquilado, accidentes de tráfico, etc.",
    "Política de Privacidad: a.Nos comprometemos a proteger su privacidad y a cumplir con todas las leyes y regulaciones aplicables relacionadas con la protección de datos personales.",
    "Legislación Aplicable: a.Estos términos y condiciones se rigen por las leyes del país en el que opera nuestro sitio web. b.Cualquier disputa relacionada con estos términos y condiciones estará sujeta a la jurisdicción exclusiva de los tribunales competentes en el lugar de operación de nuestro sitio web.",
    "Modificaciones de los Términos y Condiciones: a.Nos reservamos el derecho de modificar estos términos y condiciones en cualquier momento sin previo aviso. b.Se le notificará cualquier cambio en los términos y condiciones a través de nuestro sitio web.",
    "Al utilizar nuestros servicios, usted acepta cumplir con estos términos y condiciones. Si tiene alguna pregunta o inquietud, no dude en ponerse en contacto con nuestro equipo de atención al cliente.",
]

export const copyright = "©️ 2024 ArrancAR. Todos los derechos reservados. El contenido de esta página web, incluyendo textos, imágenes, gráficos y logotipos, está protegido por las leyes de propiedad intelectual y no puede ser reproducido, distribuido, transmitido, exhibido, publicado o transmitido de ninguna manera sin el previo consentimiento por escrito de ArrancAR. Todas las marcas comerciales mencionadas en esta página web son propiedad de sus respectivos dueños."