name: Build and Deploy React Frontend

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow on
  pull_request:
    branches:
      - main

jobs:
  Build and Deploy:
    runs-on: self-hosted
    steps:
      - name: Set Up git
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          # Stop backend service
          sudo systemctl stop arrancar-api.service || true
          sudo cp -r /home/ubuntu/deploying/* /var/www/html/
          npm install
          npm run build
          sudo systemctl stop arrancar-api.service || true
          # Start the backend service
          sudo systemctl start arrancar-api.service

      - name: Deploy
        run: |
          cd ./dist
          sudo cp -r * /var/www/html/

